contents/urls.py
from django.urls import path
from .views import PostListView, PostDetailView, PostUpdateView

app_name, urlpatterns = "contents", [
    path('', PostListView.as_view(), name="home"),
    path('<uuid:id>/', PostDetailView.as_view(), name="detail"),
    path('<uuid:id>/update/', PostUpdateView.as_view(), name="update"),
]

twitter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from .settings import MEDIA_ROOT, MEDIA_URL

urlpatterns = [
    path('admin/', admin.site.urls),
    path('contents/', include('contents.urls', namespace="contents")),
    path('accounts/', include('accounts.urls', namespace="accounts")),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

contents/models.py
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from core.models import (
    BaseModel,
    SoftDeleteModel,
    TimeStampMixin,
)

# Create your models here.
class Tag(BaseModel):
    text = models.CharField(max_length=10)

    def __str__(self) -> str:
        return self.text


class Post(TimeStampMixin, SoftDeleteModel):

    class Meta:
        verbose_name = _("Post")
        verbose_name_plural = _("Posts")

    class Statuses(models.TextChoices):
        DRAFT = "D", _("Draft")
        PUBLISHED = "P", _("Published")

    title = models.CharField(verbose_name=_("Title"), max_length=124)
    text = models.TextField(verbose_name=_("Body"), help_text=_("Text to display"))
    user = models.ForeignKey(
        "accounts.User",
        on_delete=models.CASCADE,
        related_name="posts",
    )
    status = models.CharField(
        max_length=1,
        choices=Statuses.choices,
        default=Statuses.PUBLISHED,
    )
    tags = models.ManyToManyField(Tag, related_name="posts")

    def get_url(self):
        return reverse('contents:detail', args=(self.id,))

    def __str__(self) -> str:
        return self.text


class Image(BaseModel):
    photo = models.FileField(upload_to="posts/images/")
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="images")


class Comment(TimeStampMixin, BaseModel):
    text = models.CharField(max_length=128)
    user = models.ForeignKey("accounts.User", on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    reply_to = models.ForeignKey(
        "self",
        null=True,
        blank=True,
        on_delete=models.CASCADE,
    )


class Reaction(BaseModel):
    user = models.ForeignKey("accounts.User", on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

contents/forms.py
from django import forms
from .models import Post, Comment


class PostUpdateForm(forms.ModelForm):

    class Meta:
        model = Post
        # fields = ("title", "text")
        exclude = ["user", "is_deleted"]


class CommentForm(forms.ModelForm):
    
    class Meta:
        model = Comment
        fields = ("text",)

contents/views.py
from typing import Any
from django import http
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator
from django.views import View
from .models import Post
from .forms import PostUpdateForm, CommentForm

# Create your views here.
class PostListView(View):

    def get(self, request):
        print(request.user)
        posts = Post.objects.all()
        return render(
            request,
            "contents/index.html",
            context={
                "posts":posts,
            },
        )


class PostDetailView(View):

    comment_form = CommentForm

    def setup(self, request, id):
        self.this_post = get_object_or_404(Post, id=id)
        return super().setup(request, id)

    def get(self, request, id):
        comments = self.this_post.comment_set.all()
        return render(
            request,
            "contents/detail.html",
            context={
                "post":self.this_post,
                "comments":comments,
                "comment_form": self.comment_form(),
            },
        )

    def post(self, request, id):
        form = self.comment_form(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user, comment.post = request.user, self.this_post
            comment.save()
            return JsonResponse(
                {
                    "text": comment.text,
                    "username": comment.user.username,
                }
            )


class PostUpdateView(View):

    def setup(self, request, id):
        self.this_post = get_object_or_404(Post, id=id)
        return super().setup(request, id)

    def dispatch(self, request, id):
        print(request.user.id)
        if self.this_post.user.id != request.user.id:
            return redirect("contents:home")

        return super().dispatch(request, id)

    def get(self, request, id):
        form = PostUpdateForm(instance=self.this_post)
        return render(
            request,
            "contents/update.html",
            context={
                "form":form,
            },
        )

    def post(self, request, id):
        form = PostUpdateForm(
            request.POST,
            request.FILES,
            instance=self.this_post,
        )
        if form.is_valid():
            form.save()
            return redirect("contents:detail", self.this_post.id)

        return render(
            request,
            "contents/update.html",
            context={
                "form":form,
            },
        )

templates/contents/detail.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}

{% if post.user.id == request.user.id %}
    <a href="{% url 'contents:update' post.id %}">{% trans "Update" %}</a>
{% endif %}

<h2>{{ post.title }}</h2><hr/>
<p>{{ post.user.username }}</p>
<p>{{ post.text }}</p><hr/>

{% if request.user.is_authenticated %}
    <form id="new-comment">
        {% csrf_token %}
        {{ comment_form.as_p }}
    </form>
    <button onclick="SendComment('{{ post.get_url }}')">{% trans "Send" %}</button>
{% endif %}

    <div id="comments">
        {% for comment in comments %}
            <div class="card bg-dark text-white">
                <p class="card-header">{{ comment.user }}</p>
                <p class="card-body">{{ comment.text }}</p>
            </div><br/>
        {% empty %}
            <p>No comments yet!</p>
        {% endfor %}
    </div>

{% endblock %}

{% block extra_js %}
<script>
function SendComment(url) {
    $.post(
        url, $("#new-comment").serialize(), function (result) {
            var newComment = document.createElement("div");
            newComment.className = "card bg-dark text-white";

            var username = document.createElement("p");
            username.innerHTML = result.username;
            username.className = "card-header";

            var body = document.createElement("p");
            body.innerHTML = result.text;
            body.className = "card-body";

            newComment.appendChild(username);
            newComment.appendChild(body);

            document.getElementById("comments").appendChild(newComment);
            document.getElementById("comments").appendChild(
                document.createElement("br")
            );
            document.getElementById("id_text").value = '';
        }
    )
}
</script>
{% endblock %}

templates/contents/index.html
{% extends 'base.html' %}

{% block title %} Post List {% endblock %}
{% block content %}

    <div class="card">
        {% for post in posts %}
            <a href="{{ post.get_url }}" class="card-body">{{ post.title }}</a>
        {% endfor %}
    </div>

{% endblock %}

templates/contents/update.html
{% extends 'base.html' %}

{% block title %} Update {% endblock %}
{% block content %}

    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>

{% endblock %}